### ISSUE TITLE
1.1 roadmap

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#479]
## Localization 
- [x] Localization core
- [x] Polish localization
- [x] German localization
- [ ] Russian Localization

## Bugs (Probably will be released before 1.1, as a patch)
- [x] #477 
- [x] #476 
- [x] #475 
- [ ] #473 
- [x] #440 
- [x] #483 
- [x] #494 
- [x] #501 
- [x] .pixi file association on Steam Release

## Features
- [ ] #456 

## Improvements
- [x] #480
- [x] Pipelines auto zip installer as a artifact
- [ ] #471 
- [ ] MSIX build in PixiEditor.Builder

**Comment by CPKreu** [comment]
1.1 has been released btw
